version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  web-server:
    build: .
    restart: always
    ports:
      - 80:80
    depends_on: 
      - mongo