version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  web:
    build: .
    restart: always
    ports:
      - 80:80
    depends_on: 
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development